export const INDUSTRIES = [
  "Real Estate",
  "Home Loans",
  "Personal Loans",
  "Car Loans",
  "Insurance",
  "Construction",
  "Interior Design",
  "Architecture",
  "Legal Services",
  "Accounting",
  "Education",
  "Healthcare",
  "IT Services",
  "Digital Marketing",
  "Manufacturing",
  "Logistics",
  "Automobile",
];
